app = "shadow-roll-bot"
primary_region = "cdg"

[build]
  builder = "paketobuildpacks/builder:base"
  buildpacks = ["gcr.io/paketo-buildpacks/python"]

[env]
  LOG_LEVEL = "INFO"

[processes]
  worker = "python main.py"

[[mounts]]
  source = "shadow_roll_data"
  destination = "/app/data"

[deploy]
  strategy = "immediate"